apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  labels:
    app: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "licmanager-core"
        dapr.io/app-port: "8090"
        dapr.io/azure-workload-identity-enabled: "true"
      labels:
        app: core
        azure.workload.identity/use: "true"
    spec:
      nodeSelector:
        kubernetes.azure.com/mode: user
        beta.kubernetes.io/os: linux
      serviceAccountName: aks-learning-sa
      containers:
      - name: core
        image: '#fullImagePath#'
        ports:
        - containerPort: 8080
          name: corehttp
          protocol: TCP
        - containerPort: 8090
          name: health
          protocol: TCP
        volumeMounts:
        - name: appsettings
          mountPath: /app/configs
        - name: secrets-store
          mountPath: /app/certs
          readOnly: true
#        livenessProbe:
#          httpGet:
#            path: /health/live
#            port: 8090
#          initialDelaySeconds: 3
#          periodSeconds: 3
#        readinessProbe:
#          httpGet:
#            path: /health/ready
#            port: 8090
#          initialDelaySeconds: 1
#          timeoutSeconds: 1
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "#environment#"  
      volumes:
      - name: appsettings
        configMap:
          name: coresettings
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-keyvault-provider # Reference to the SecretProviderClass
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  selector:
    app: core
  type: ClusterIP
  ports:
  - port: 80
    targetPort: corehttp
    name: corehttp
  - port: 8090
    targetPort: health
    name: health
---
